FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/MsTransacoes.API/MsTransacoes.API.csproj", "MsTransacoes.API/"]
COPY ["src/MsTransacoes.Application/MsTransacoes.Application.csproj", "MsTransacoes.Application/"]
COPY ["src/MsTransacoes.Domain/MsTransacoes.Domain.csproj", "MsTransacoes.Domain/"]
COPY ["src/MsTransacoes.Infra/MsTransacoes.Infra.csproj", "MsTransacoes.Infra/"]
RUN dotnet restore "MsTransacoes.API/MsTransacoes.API.csproj"

COPY src/ .
RUN dotnet publish "MsTransacoes.API/MsTransacoes.API.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "MsTransacoes.API.dll"]
